# Generated by Django 4.2.6 on 2023-10-23 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceParameterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rarity', models.CharField(max_length=20)),
                ('Type', models.CharField(max_length=20)),
            ],
        ),
    ]
