# Generated by Django 4.2.6 on 2023-10-18 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('ExchangeID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
                ('DecimalValue', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('ItemID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('LocationID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
                ('URL', models.URLField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rarity',
            fields=[
                ('RarityID', models.AutoField(primary_key=True, serialize=False)),
                ('Rarity', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Scrapes',
            fields=[
                ('ScrapeID', models.AutoField(primary_key=True, serialize=False)),
                ('Availability', models.IntegerField()),
                ('Transaction', models.CharField(max_length=10)),
                ('ExchangeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='View.exchange')),
                ('ItemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='View.item')),
                ('LocationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='View.location')),
                ('RarityID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='View.rarity')),
            ],
        ),
    ]
