# Generated by Django 4.2.6 on 2023-10-18 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('View', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Scrapes',
            new_name='Scrape',
        ),
    ]
