# Generated by Django 4.2.6 on 2023-10-19 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('View', '0002_rename_scrapes_scrape'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('CurrencyID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
            ],
        ),
    ]
