# Generated by Django 4.2.6 on 2023-10-20 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('View', '0004_scrape_currencyid'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Class',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='Equip',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='scrape',
            name='Level',
            field=models.CharField(default='', max_length=10),
        ),
    ]
