# Generated by Django 4.2.6 on 2023-10-20 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('View', '0005_item_class_item_equip_scrape_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrape',
            name='Date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='scrape',
            name='Painted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scrape',
            name='Price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
