# Generated by Django 4.2.6 on 2023-10-20 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('View', '0006_scrape_date_scrape_painted_scrape_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Class',
            field=models.CharField(default='', max_length=50),
        ),
    ]
